spring:
  profiles:
    active: local
  application:
    name: NoteZen
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - openid
              - profile
              - email
              - https://www.googleapis.com/auth/business.manage
            redirect-uri: "{baseUrl}/login/oauth2/code/google"

app:
  version: "1.2.1"

logging:
  level:
    ROOT: INFO
    com.bchev.notezen: DEBUG