spring:
  # Configuration H2
  datasource:
    url: jdbc:h2:mem:googledb
    driverClassName: org.h2.Driver
    username: sa
    password: zeaz
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
              - https://www.googleapis.com/auth/business.manage  # LE SCOPE CRUCIAL
            redirect-uri: "{baseUrl}/login/oauth2/code/google"


  application:
    name: NoteZen
google:
  client-id: ${GOOGLE_CLIENT_ID:dummy_id}
  client-secret: ${GOOGLE_CLIENT_SECRET:dummy_secret}
  redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/google/callback}

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    ROOT: INFO