spring:
  # Configuration H2
  datasource:
    url: jdbc:h2:mem:googledb
    driverClassName: org.h2.Driver
    username: sa
    password: zeaz
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "dummy_id"
            client-secret: "dummy_secret"
            scope:
              - openid
              - profile
              - email
              - https://www.googleapis.com/auth/business.manage  # LE SCOPE CRUCIAL
            redirect-uri: "{baseUrl}/login/oauth2/code/google"


  application:
    name: NoteZen
google:
  client-id: "dummy_id"
  client-secret: "dummy_secret"
  redirect-uri: "http://localhost:8080/api/google/callback"
  ai:
    api:
      key: "dummy_key"

jwt:
  secret: "dummy_jwt"

app:
  version: "1.2.1"
  mock-user-email: "bchevriaut@gmail.com"

front:
  url: "https://www.notezen.fr/"

logging:
  level:
    ROOT: INFO